import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavbarTop from "@/components/layouts/navbar-top";
import Providers from "@/components/providers";
import SidebarLeft from "@/components/layouts/sidebar-left";
import SidebarRight from "@/components/layouts/sidebar-right";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  manifest: "/manifest.json",
  title: {
    template: "%s",
    default: "Quran",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <NavbarTop />
          <div className="max-w-7xl mx-auto">
            {/* <div className="grid grid-cols-2 md:grid-cols-4 h-screen"> */}
            {/* <SidebarLeft className="col-span-1 hidden md:block overflow-auto scrollbar-hidden" /> */}
            <main className="pt-16 overflow-auto min-h-screen pb-10 scrollbar-hidden">
              {children}
            </main>
            {/* <SidebarRight className="col-span-1 hidden md:block overflow-auto scrollbar-hidden" /> */}
            {/* </div> */}
          </div>
        </Providers>
      </body>
    </html>
  );
}
